### PR TITLE
Testcontainers via test-resources version catalog

### PR DESCRIPTION
**Pull request by wetted**

### CODE REVIEW

**Comment by timyates** [comment]
Docker (and testcontainers) *hates* restarting a container on the previous port

And the `AbstractRabbitMQClusterTest` is a horrible smell as all the static stuff is effectively static global state 😬 

As a quick patchy fix, we can do the following to stop trying to guess ports to put the rabbit clusters on (this no longer works anyway with the `RabbitMQContainer` as it has many, many ports that it exposes instead of the one previously)

```diff
diff --git a/rabbitmq/src/test/groovy/io/micronaut/rabbitmq/AbstractRabbitMQClusterTest.groovy b/rabbitmq/src/test/groovy/io/micronaut/rabbitmq/AbstractRabbitMQClusterTest.groovy
index ea7fed43..33b5af2c 100644
--- a/rabbitmq/src/test/groovy/io/micronaut/rabbitmq/AbstractRabbitMQClusterTest.groovy
+++ b/rabbitmq/src/test/groovy/io/micronaut/rabbitmq/AbstractRabbitMQClusterTest.groovy
@@ -41,24 +41,30 @@ abstract class AbstractRabbitMQClusterTest extends Specification {
     static int node3Port

     static {
-        getNodePorts()
         log.info("rabbit.conf path: {}", RABBIT_CONFIG_PATH)
         log.info("rabbit definitions path: {}", RABBIT_DEFINITIONS_PATH)
-        log.info("rabbit node ports: {}, {}, {}", node1Port, node2Port, node3Port)

-        configureContainer(NODE1_CONT, "rabbitmq1", node1Port)
+        configureContainer(NODE1_CONT, "rabbitmq1")
         // first node must boot up completely so that the other nodes can join the new cluster
         NODE1_CONT.waitingFor(Wait.forHealthcheck().withStartupTimeout(Duration.ofMinutes(1)))
         NODE1_CONT.start()
+        node1Port = NODE1_CONT.getMappedPort(AMQP_PORT)
+
         log.info("first node startup complete")

-        configureContainer(NODE2_CONT, "rabbitmq2", node2Port)
-        configureContainer(NODE3_CONT, "rabbitmq3", node3Port)
+        configureContainer(NODE2_CONT, "rabbitmq2")
+        configureContainer(NODE3_CONT, "rabbitmq3")
         // node 2 and 3 may start up in parallel as they can join the already existing cluster
         NODE2_CONT.waitingFor(new DoNotWaitStrategy())
         NODE3_CONT.waitingFor(new DoNotWaitStrategy())
         NODE2_CONT.start()
         NODE3_CONT.start()
+
+        node2Port = NODE2_CONT.getMappedPort(AMQP_PORT)
+        node3Port = NODE3_CONT.getMappedPort(AMQP_PORT)
+
+        log.info("rabbit node ports: {}, {}, {}", node1Port, node2Port, node3Port)
+
         new PollingConditions(timeout: 60).eventually {
             assert NODE2_CONT.isHealthy()
             assert NODE3_CONT.isHealthy()
@@ -81,17 +87,7 @@ abstract class AbstractRabbitMQClusterTest extends Specification {
         applicationContext?.close()
     }

-    private static getNodePorts() {
-        try (ServerSocket s1 = new ServerSocket(0)
-             ServerSocket s2 = new ServerSocket(0)
-             ServerSocket s3 = new ServerSocket(0)) {
-            node1Port = s1.localPort
-            node2Port = s2.localPort
-            node3Port = s3.localPort
-        }
-    }
-
-    private static configureContainer(RabbitMQContainer mqContainer, String hostname, int nodePort) {
+    private static configureContainer(RabbitMQContainer mqContainer, String hostname) {
         mqContainer
                 .withEnv("RABBITMQ_ERLANG_COOKIE", CLUSTER_COOKIE)
                 .withCopyFileToContainer(forHostPath(RABBIT_CONFIG_PATH), "/etc/rabbitmq/rabbitmq.conf")
@@ -106,15 +102,6 @@ abstract class AbstractRabbitMQClusterTest extends Specification {
                                 .withInterval(Duration.ofSeconds(5).toNanos())
                                 .withRetries(10)
                                 .withTimeout(Duration.ofSeconds(5).toNanos())))
-        // Use fixed port binding, because the dynamic port binding would use different port on each container start.
-        // These changing ports would make any reconnect attempt impossible, as the client assumes that the broker
-        // address does not change.
-        addPortBinding(mqContainer, nodePort, AMQP_PORT)
-    }
-
-    private static addPortBinding(RabbitMQContainer cont, int hostPort, int contPort) {
-        cont.portBindings << String.format("%d:%d/%s",
-                hostPort, contPort, InternetProtocol.TCP.toDockerNotation())
     }

     private static class DoNotWaitStrategy extends AbstractWaitStrategy {
```

This stops using `ServerSocket(0)`, and instead just runs the containers and captures their amq ports

Then, to restart, instead of stopping the container and restarting it with some hacks to hardcode the port (which are brittle, and some I found on the internet no longer seem to work), we can reach into the container, and stop Rabbit itself with

```diff
diff --git a/rabbitmq/src/test/groovy/io/micronaut/rabbitmq/listener/ConsumerRecoverySpec.groovy b/rabbitmq/src/test/groovy/io/micronaut/rabbitmq/listener/ConsumerRecoverySpec.groovy
index 9799df60..fcc3c892 100644
--- a/rabbitmq/src/test/groovy/io/micronaut/rabbitmq/listener/ConsumerRecoverySpec.groovy
+++ b/rabbitmq/src/test/groovy/io/micronaut/rabbitmq/listener/ConsumerRecoverySpec.groovy
@@ -219,10 +219,8 @@ class ConsumerRecoverySpec extends AbstractRabbitMQClusterTest {

     private static restartContainer(GenericContainer container) throws InterruptedException {
         log.info("stopping container: {}", container.containerId)
-        DOCKER_CLIENT.stopContainerCmd(container.containerId).exec()
-
-        log.info("re-starting container: {}", container.containerId)
-        DOCKER_CLIENT.startContainerCmd(container.containerId).exec()
+        container.execInContainer("rabbitmqctl", "stop_app")
+        container.execInContainer("rabbitmqctl", "start_app")

         new PollingConditions(timeout: 60).eventually {
             container.isHealthy()
```

**Comment by timyates** [comment]
Also is there a reason we don't use the official RabbitMQ docker image 🤔

**Comment by wetted** [comment]
@timyates thanks for all your help. This works now. It still needs some work to get rid of code smells. Also, newer Docker images break the test again, and I'm not yet sure why. The latest is rabbitmq:3.13.0-management.

**Review by timyates — APPROVED** [review]
Approved!  I pushed a commit to get rid of the static containers and stuff that could just be shared variables

The issues you're seeing with later rabbit versions are probably what all the warnings are on about in the logs when rabbit starts up:

```
[rabbitmq2] STDERR: WARNING: '/var/lib/rabbitmq/.erlang.cookie' was populated from '$RABBITMQ_ERLANG_COOKIE', which will no longer happen in 3.9 and later! (https://github.com/docker-library/rabbitmq/pull/424)
[rabbitmq2] STDERR: touch: cannot touch '/etc/rabbitmq/rabbitmq.conf': Permission denied
[rabbitmq2] STDERR: 
[rabbitmq2] STDERR: WARNING: '/etc/rabbitmq/rabbitmq.conf' is not writable, but environment variables have been provided which request that we write to it
[rabbitmq2] STDERR:   We have copied it to '/tmp/rabbitmq.conf' so it can be amended to work around the problem, but it is recommended that the read-only source file should be modified and the environment variables removed instead.
[rabbitmq2] STDERR: 
[rabbitmq2] STDERR: WARNING: 'docker-entrypoint.sh' generated/modified the RabbitMQ configuration file, which will no longer happen in 3.9 and later! (https://github.com/docker-library/rabbitmq/pull/424)
[rabbitmq2] STDERR: 
[rabbitmq2] STDERR: Generated end result, for reference:
[rabbitmq2] STDERR: ------------------------------------
[rabbitmq2] STDERR: loopback_users.guest = false
[rabbitmq2] STDERR: listeners.tcp.default = 5672
[rabbitmq2] STDERR: management.tcp.port = 15672
[rabbitmq2] STDERR: 
[rabbitmq2] STDERR: consumer_timeout = 5000
[rabbitmq2] STDERR: 
[rabbitmq2] STDERR: management.load_definitions = /etc/rabbitmq/definitions.json
[rabbitmq2] STDERR: 
[rabbitmq2] STDERR: cluster_formation.peer_discovery_backend = classic_config
[rabbitmq2] STDERR: cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq1
[rabbitmq2] STDERR: cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq2
[rabbitmq2] STDERR: cluster_formation.classic_config.nodes.3 = rabbit@rabbitmq3
[rabbitmq2] STDERR: default_pass = guest
[rabbitmq2] STDERR: load_definitions = /etc/rabbitmq/definitions.json
[rabbitmq2] STDERR: ------------------------------------
```

**Pull request merged**
